Feature/payment widget
atls/reactjs pull request #123
Opened 2023-07-31 10:44 UTC by KentCpu

После долгих раздумий решил погуглить. Нашел схожий функционал у "ЮKassa". Они предоставляют конструктор формы с обязательными полями и возможностью добавления дополнительных. Я попытался реализовать нечто подобное в коде. Что касается стилей, я заметил, что они обычно фиксированы для таких форм. Смог получить доступ к функции "pay", но мне кажется, что это костыль.

Прошу ответить на следующие вопросы:

1. Правильно ли я понимаю, что стили обычно фиксированы для таких форм, или следует предоставить возможность для их стилизации?
2. Как можно было получить доступ к функции pay по другому ? Смог сделать только [так](https://github.com/atls/reactjs/blob/6d4eebcfb0d9bb6ec5970f5910c0dcd0c44cbdbc/packages/payment-widget/src/payment-widget.hook.tsx#L24C4-L24C4)

2023-07-31 12:55 UTC, TorinAsakura requested changes
- Обрати внимание на отсутствие последних строк
- использований нативных хтмл компонентов - запрещено, как ты потом будешь с ним работать? через some.ref[div]? Используй нашу библиотеку github.com/atls/hyperion
- все сообщения, должны быть в формате intl, пример есть в github.com/torin-asakura/drumin, ищи FormattedMessage
- далее, у нас отступы 2, а у тебя 4, код выглядит раздутым, используй пожалуйста yarn check перед тем как коммитить
- пожалуйста, используй систему монорепозиториев, посмотри как выполнены плагины рядом
- в packages/payment-widget/src/payment-widget.hook.tsx намешано всё подряд, так делать не нужно, разбивай на ответственные зоны: change.handler.ts, init.hook.ts (туда можешь вынести инициализацию document.createElement)
- всевозможные ошибки должны быть вынесены в слой exception, пример https://github.com/atls/nestjs/blob/cf76057580570b056a033569ff37ac7bac9f0070/packages/grpc-errors/src/exception-factories/grpc-validation.exception-factory.ts#L23

2023-08-04 20:37 UTC, Nelfimov requested changes
Необходимо доработать.

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-widget.component.tsx
> +        Оплатить
Зашил русскую кнопку.

@torinasakura, в пакете уместно использовать `react-intl`, обернув `form` в локальный провайдер?

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/utils/init.util.ts
> +      reject(new Error('Failed to load Tinkoff Cashier script.'))
Правильнее будет Tinkoff Pay или Tinkoff Widget.

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-widget.component.tsx
> +      <PaymentSettings storeId={settings.storeId} />
`PaymentSettings` готов принять больше пропсов, а мы передаем хоть и самый важный, но только один. Кастомизация ведь должна быть.

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    placeholder: 'Сумма заказа',
Зашил русскую строку.

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-widget.component.tsx
> +    <form>
По документации должно быть `name="payform-tinkoff"`.

2023-08-04 20:37 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-settings.component.tsx
> +      {generateReceipt && <HiddenInput name='receipt' defaultValue='' />}
Нет функционала чека, надо добавить.

2023-08-04 23:22 UTC, TorinAsakura commented on packages/payment-widget/src/ui/payment-widget.component.tsx
> +        Оплатить
> Зашил русскую кнопку.
> 
> @TorinAsakura, в пакете уместно использовать `react-intl`, обернув `form` в локальный провайдер?

Не, уместно, а необходимо.

2023-08-09 14:08 UTC, Nelfimov requested changes
Хороший прогресс, работаем дальше.

2023-08-09 14:08 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +        type={field.type ?? 'text'}
Давай добавим class как в доке для кастомизации через CSS - "payform-tinkoff-row"

2023-08-09 14:08 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-settings.component.tsx
> +      <HiddenInput name='terminalkey' defaultValue={storeId} />
Давай добавим в инпуты тоже классы для кастомизации через CSS как в доке - "payform-tinkoff-row"

2023-08-11 18:35 UTC, Nelfimov requested changes
Нужны правки.

Для стилей рекомендую выносить в пропсы как отдельные объекты, например `direction`, `buttonStyle`, `inputGaps` и т.д.

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-fields.component.tsx
> +      <Condition match={!!amount}>
По интерфейсу у тебя `amount` всегда есть. Если его сделать = 0, то все работает, но такая проверка неинтуитивна. Предлагаю сделать `amount` необязательным.

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/interfaces/payment-widget.interfaces.ts
> +  amount: number
Обязательный параметр, см. комментарии далее в fields.

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-fields.component.tsx
> +      <Condition match={!amount}>{useFields(requiredFields, fieldStyle)}</Condition>
Лучше вынеси этот хук в константу по аналогии с `fieldsWithReceipt`.

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-settings.component.tsx
> +    language = Languages.RUSSIAN,
Не работает английский язык - кнопка остается "Оплатить".

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +      <Input
Давай начнем кастомизацию стилей - как минимум предложим сделать гэпы между инпутами и направление полей. Гэпы давай делать через компонент `Layout` в `@atls-ui-parts/layout`, а направление через тот же пакет но компоненты `Row`/`Column`.

2023-08-11 18:35 UTC, Nelfimov commented on packages/payment-widget/src/ui/payment-form.component.tsx
> +      <Button
Давай добавлять кастомизацию для кнопки - здесь можно экспортировать функции из `@atls-ui-parts/button`.

2023-08-15 16:51 UTC, KentCpu commented
@Nelfimov, добавил темы для кнопок. Возможно, стоит также добавить темы для инпутов? Странно, что тесты не прошли, так как у меня yarn check выполнился без ошибок.

2023-08-15 17:05 UTC, Nelfimov commented
> @Nelfimov, добавил темы для кнопок. Возможно, стоит также добавить темы для инпутов? Странно, что тесты не прошли, так как у меня yarn check выполнился без ошибок.

У тебя две папки с темой - `src/payment-theme` и `src/theme`. При этом в первой есть только провайдер, а во второй - только цвета.

Ты видимо чутка заработался.

По инпутам - можно сделать легкую тему с подсветкой границ при активности.

2023-08-18 06:57 UTC, KentCpu commented
@Nelfimov, я решил отказаться от идеи с темой для кнопки, так как это выглядело не очень органично. Вместо этого, я использовал стили из формы для оплаты и добавил валидацию. Жду ревью :)

2023-08-21 10:15 UTC, Nelfimov requested changes

2023-08-21 13:32 UTC, Nelfimov approved these changes
👍

2023-08-22 16:32 UTC, TorinAsakura commented on packages/payment-widget/src/ui/payment-input/payment-input.component.tsx
> +      onBlur={() => {
@KentCpu статус?

2023-08-22 16:33 UTC, KentCpu commented on packages/payment-widget/src/ui/payment-input/payment-input.component.tsx
> +      onBlur={() => {
@TorinAsakura виджет вроде бы готов, Никита одобрил, жду твоего ревью.

2023-08-22 21:46 UTC, TorinAsakura requested changes

2023-08-22 21:46 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-init.hook.ts
> +import { useEffect } from 'react'
Не вижу проверок на успешную загрузку скрипта. Давай сделаем что-то в духе
```typescript
export const useInit = () => {
  const [isLoaded, setIsLoaded] = useState(false)
  const TINKOFF_SCRIPT_URL = 'https://securepay.tinkoff.ru/html/payForm/js/tinkoff_v2.js'

  useEffect(() => {
    // Проверка, загружен ли скрипт уже
    if (document.querySelector(`script[src="${TINKOFF_SCRIPT_URL}"]`)) {
      setIsLoaded(true)
      return
    }

    const script = document.createElement('script')
    script.src = TINKOFF_SCRIPT_URL
    script.async = true

    script.onload = () => setIsLoaded(true)
    script.onerror = () => {
      console.error('Ошибка загрузки скрипта:', TINKOFF_SCRIPT_URL)
      // Здесь можно добавить дополнительную логику обработки ошибок
    }

    document.body.appendChild(script)

    return () => {
      document.body.removeChild(script)
    }
  }, [TINKOFF_SCRIPT_URL])

  return isLoaded
}
```

2023-08-22 21:46 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
Меня беспокоит смешение логики и представления: Хук здесь занимается и управлением состоянием полей, и их рендерингом. Это может усложнить тестирование и переиспользование. Возможно, стоит разделить этот хук на две части: одну для управления состоянием полей и валидации, а другую для рендеринга.

Что касается оптимизации рендеринга то в текущей реализации при каждом изменении одного из полей будет происходить перерендеринг всех полей. Это может привести к проблемам с производительностью.

2023-08-22 21:46 UTC, TorinAsakura commented on packages/payment-widget/src/ui/index.ts
> +export * from './payment-widget.component'
я бы не стал добавлять префикс, мы вынесем этот компонент в отдельную репу тинькофф библиотек, так что можешь смело убирать payment-

2023-08-23 14:05 UTC, KentCpu commented on packages/payment-widget/src/hooks/use-init.hook.ts
> +import { useEffect } from 'react'
@TorinAsakura, разве проверка, загружен ли скрипт, не избыточна? useEffect отрабатывает после монтирования единожды и при размонтировании вызывается функция очистки, которая удаляет скрипт. Однако если у нас на странице несколько наших виджетов, то мы избежим ненужных загрузок. Я правильно понимаю, что мы добавляем эту проверку для этого?

2023-08-23 14:08 UTC, KentCpu commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
@TorinAsakura, правильно ли я понимаю, что для того чтобы избежать ненужных перерендеров, нам нужно локализовать стейт? Например, можно было бы создать отдельный компонент для поля.

2023-08-23 14:54 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
> @TorinAsakura, правильно ли я понимаю, что для того чтобы избежать ненужных перерендеров, нам нужно локализовать стейт? Например, можно было бы создать отдельный компонент для поля.

Можно использовать React.memo или другие методы оптимизации для уменьшения количества ненужных перерендерингов.

2023-08-23 14:56 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-init.hook.ts
> +import { useEffect } from 'react'
> @TorinAsakura, разве проверка, загружен ли скрипт, не избыточна? useEffect отрабатывает после монтирования единожды и при размонтировании вызывается функция очистки, которая удаляет скрипт. Однако если у нас на странице несколько наших виджетов, то мы избежим ненужных загрузок. Я правильно понимаю, что мы добавляем эту проверку для этого?

Да, ты правильно понимаешь. Проверка на наличие скрипта в DOM полезна в случае, если хук `useInit` может быть использован в нескольких местах одновременно или если компонент, использующий этот хук, может маунтиться/анмаунтиться несколько раз.

Если на странице несколько экземпляров виджета, и каждый из них пытается загрузить один и тот же скрипт, это может привести к ненужным запросам и потенциальным проблемам. Проверка на наличие скрипта в DOM перед добавлением нового экземпляра скрипта помогает избежать этого, гарантируя, что скрипт будет загружен только один раз.

Так что да, добавление этой проверки помогает избежать ненужных загрузок и делает код более надёжным в сценариях, когда хук может быть использован в нескольких местах на странице.

2023-08-24 06:49 UTC, KentCpu commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
@TorinAsakura нашёл первопричину перендоров полей: это состояние с [ошибками](https://github.com/atls/reactjs/blob/afe0e30427fa016e13345d564c3feb1a74ac76d9/packages/payment-widget/src/ui/form.component.tsx#L16) в компоненте формы. Поля проходят валидацию при onBlur, ошибка меняется, и форма выполняет перерисовку. Насколько это критично, учитывая, что у нас такая маленькая форма?

2023-08-24 12:13 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
Не важен размер, важно удобство работы с этим решением. На фикс уйдёт много времени?

2023-08-24 13:29 UTC, KentCpu commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
@TorinAsakura, я разделил управление состоянием и рендерингом, но пока не знаю, как исправить проблему с лишним перерендерингом. В любом случае нам придется хранить состояние с ошибками в форме, иначе мы не сможем проверить правильность отправляемых данных. Может быть, у тебя есть идеи, как это можно исправить?

2023-08-24 13:45 UTC, TorinAsakura commented on packages/payment-widget/src/hooks/use-fields.hook.tsx
> +    return (
Так, ну я уже ведь тебе писал про memo, не понимаю вопроса, но, если тебе мало memo то есть и другие методы:

1. **Использование `React.memo`**: Если ты вынес рендеринг полей в отдельный компонент, можно обернуть этот компонент в `React.memo`. Это гарантирует, что компонент будет перерендериваться только при изменении пропсов.

   ```typescript
   const FieldComponent = React.memo(({ field, error, onChange, onBlur }) => {
     // Рендеринг поля
   })
   ```

2. **Оптимизация функций-обработчиков**: Если функции-обработчики создаются внутри рендер-метода, они будут создаваться заново при каждом рендеринге, что может вызвать перерендеринг дочерних компонентов. Использование `useCallback` может помочь избежать этого.

   ```typescript
   const handleChange = useCallback((name, value) => {
     // Обработка изменения
   }, [/* зависимости */]);

   const handleBlur = useCallback((name, value, required) => {
     // Обработка потери фокуса
   }, [/* зависимости */]);
   ```

3. **Оптимизация объектов состояния**: Если объекты состояния создаются заново при каждом рендеринге, это также может вызвать лишние перерендеринги. Использование `useMemo` или хранение состояния в отдельных переменных с использованием `useState` может помочь.

   ```typescript
   const [fieldState, setFieldState] = useState(/* исходное состояние */);
   const errors = useMemo(() => /* вычисление ошибок */, [/* зависимости */]);
   ```

Эти методы можно комбинировать в зависимости от конкретной ситуации и требований к производительности. Основная цель здесь — убедиться, что компоненты и данные, которые не изменились, не пересоздаются и не перерендериваются заново.

2023-08-25 08:41 UTC, Nelfimov approved these changes

2023-08-25 16:53 UTC, TorinAsakura approved these changes

2023-08-25 16:53 UTC, merged