Feature/custom theme
atls/reactjs pull request #134
Opened 2023-11-16 13:25 UTC by absolemDev

2023-11-17 05:34 UTC, Nelfimov requested changes
В направлении одного из вариантов идешь. Главное - тестируй параллельно, а еще лучше пиши в пакете тесты - так точно убедимся в работоспособности

2023-11-17 05:34 UTC, Nelfimov commented on packages/payment-widget/src/interfaces/styles.interfaces.ts
> +  styledArray?: any[]
Почему не конкретизировать? Интерфейс же можно подсмотреть в гиперионе у кнопки и инпута

2023-11-17 05:34 UTC, Nelfimov commented on packages/payment-widget/src/ui/theme/src/theme.provider.tsx
> +export const ThemeProvider = ({ customTheme, children }) =>
Не хватает интерфейса

2023-11-20 11:45 UTC, absolemDev commented
@Nelfimov, пока что без тестов. Посмотри логику.

2023-11-20 12:39 UTC, Nelfimov requested changes

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields-render.hook.tsx
> +import { CustomInput }       from '../interfaces/custom-elements.interfaces'
Длинный импорт

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields-render.hook.tsx
> +  customInput: CustomInput | undefined
можно же `customInput?: ...`

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/ui/button/button.component.tsx
> +import { CustomButtonProps } from '../../interfaces/custom-elements.interfaces'
Длинный импорт

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/ui/form.component.tsx
> +  const buttonProps = {
Интерфейс

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/ui/theme/src/theme.provider.tsx
> +import { ThemeProps }                            from '../../../interfaces/theme.interfaces'
Длинный импорт

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/interfaces/custom-elements.interfaces.ts
> +}
инпут и баттон намешены в один файл. Раздели

2023-11-20 12:39 UTC, Nelfimov commented on packages/payment-widget/src/interfaces/custom-elements.interfaces.ts
> +}
Как планируешь использовать варианты?

2023-11-20 13:34 UTC, absolemDev commented on packages/payment-widget/src/interfaces/custom-elements.interfaces.ts
> +}
В данной реализации предполагается что все атрибуты/пропсы относящиеся к проекту и его теме будут описаны в самом проекте и будут передаваться в виджет. Например так:
```
<Widget
          amount={5000}
          settings={{ storeId: 'id' }}
          additionalFields={[
            {
              name: AdditionalFieldsType.Email,
              placeholder: 'Электронная почта',
              required: false,
              type: 'email',
            },
          ]}
        customElements={{
             button: (props) => {
                  <Button
                       size='withoutPaddingSemiBigHeight'
                       variant='purpleBackground'
                       fill
                       {...props}
                  >
                      <Text fontWeight='semiBold' fontSize='medium' textTransform='uppercase'>
                         {messages.send}
                     </Text>
                 </Button>
             }
        }}
/>
```

2023-11-20 14:41 UTC, Nelfimov commented on packages/payment-widget/src/interfaces/custom-elements.interfaces.ts
> +}
А почему тогда в интерфейсе только эти пропсы?

```tsx
export interface CustomButtonProps {
  type: string
  disabled: boolean
  children?: React.ReactNode
}
```

И покажи пример с их использованием.

2023-11-20 16:36 UTC, absolemDev commented on packages/payment-widget/src/interfaces/custom-elements.interfaces.ts
> +}
Это пропсы которые передаются кнопке в форме виджета
https://github.com/atls/reactjs/blob/d14b846684109f4f2b4c00bb4530822d8185312b/packages/payment-widget/src/ui/form.component.tsx#L40
И от `styles.button` тогда можем отказаться

2023-11-20 17:14 UTC, Nelfimov approved these changes

2023-11-20 21:52 UTC, TorinAsakura requested changes
понятие кастомных элементов не может работать нормально, при таком раскладе мы теряем контроль, так как кастомные элементы неизвестны и надо лезть вовнутрь

2023-11-21 12:42 UTC, absolemDev commented
@Nelfimov, сейчас пробую такой подход:
1. Из проекта беру функцию стилизации элемента и отдаю виджету:

input.component.tsx:
```
...
export const InputElement = styled.div<any>(
  baseStyles,
  shapeStyles,
  appearanceStyles,
  transitionStyles,
  layout
);

export const styledInput = InputElement.withComponent;
...
```
form-content.component.tsx:
```
...
<Widget
    amount={5000}
    settings={{ storeId: "id" }}
    additionalFields={additionalFieldsWidget}
    styles={{ styledInput }}
 />
...
```
3. В виджете по условию рендерю инпут:

input.component.tsx:
```
...
const CustomInput = styledInput ? styledInput("div") : null;

  return (
...
      {styledInput ? (
        <CustomInput {...props} error={errorText !== ""}>
          <RawInput
            ref={ref}
            type={type}
            required={required}
            disabled={disabled}
            value={value}
            onChange={changeValue}
            placeholder={required ? `${placeholder}*` : placeholder}
            {...props}
          />
        </CustomInput>
      ) : (
        <InputElement {...props} error={errorText !== ""}>
          <RawInput
            ref={ref}
            type={type}
            required={required}
            disabled={disabled}
            value={value}
            onChange={changeValue}
            placeholder={required ? `${placeholder}*` : placeholder}
            {...props}
          />
        </InputElement>
      )}
...
```
Но сталкиваюсь с такой же проблемой как если предавать массив "стилей" `[baseStyles, shapeStyles, appearanceStyles, transitionStyles, layout]`. Инпут начинает вести себя некорректно: ловит фокус только с третьего клика, теряет фокус после ввода одного символа в поле, теряет фокус если не `:hover`.

2023-11-21 13:49 UTC, Nelfimov commented
Тогда попробуй подход из соседнего пакета `next-identity-integration` - там предоставляется на компонент а функции обработчики. А их ты уже можешь вешать на свои компоненты с темой.

2023-11-23 08:52 UTC, Nelfimov requested changes
И покажи пример как ты будешь использовать враппер

2023-11-23 08:52 UTC, Nelfimov commented on packages/payment-widget/src/ui/form.component.tsx
> +export const FormContext = createContext<any>(null)
Намешал в одном файле. Раздели на отдельные блоки - контекст, хук для использования контекста. Пример можешь подсмотреть в соседних пакетах

2023-11-23 10:47 UTC, TorinAsakura requested changes
почистить any

2023-11-23 16:49 UTC, absolemDev commented
Преобразовал аргументы обертки инпута в объект

2023-11-24 05:23 UTC, Nelfimov requested changes

2023-11-24 05:23 UTC, Nelfimov commented on packages/payment-widget/src/ui/form/use-form.hook.ts
> +export const useForm = () => useContext(Context) as FieldsValidator
`as` не очень хорошо пользовать - если у тебя например контекст "потеряется", его будет передавать компонент из другого пакета. В таком случае ты об этом даже не узнаешь, увидишь только пустой контекст.

Можешь сделать так:

```tsx
export const useForm = (): FieldsValidator => {
    const context = useContext(Context)
    
    if (!context) throw new Error('Missing form context provider')
    
    return context
}
```

2023-11-24 05:23 UTC, Nelfimov commented on packages/payment-widget/src/ui/form.test.tsx
> +// /**
Тут либо удаляй либо ставь `TODO` в будущем доделать тесты

2023-11-24 05:23 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-fields-state.hook.ts
> +export const useFieldsState = (validateField: ValidateField, fields?: Field[]) => {
Нужен интерфейс возврата

2023-11-24 07:16 UTC, absolemDev commented
Добавил `disabled` в контекст формы. Для чилдрена врапера кнопки добавил аргумент: объект с ключами `type` и `disabled`

2023-11-24 07:52 UTC, Nelfimov requested changes
ну и главный вопрос - проводишь ли тесты по этим доработкам в проекте? Ведь ты можешь создать локальную копию этого пакета там же и тестировать. При изменениях тут - переносишь туда и тестируешь опять. Потом когда будет релиз виджета - просто подменишь зависимости в проекте

2023-11-24 07:52 UTC, Nelfimov commented on packages/payment-widget/src/ui/form/form.provider.tsx
> +export default FormProvider
почему как дефолт экспортируешь? Обычно экспорт поименный у нас

2023-11-24 08:27 UTC, absolemDev commented
> ну и главный вопрос - проводишь ли тесты по этим доработкам в проекте? 

Да, конечно

2023-11-24 08:36 UTC, Nelfimov approved these changes
перед запросом дальнейшего ревью залей актуальную версию виджета в драмин, посмотрю как работает

2023-11-24 15:57 UTC, absolemDev commented
@Nelfimov, залил в драмин

2023-11-26 20:30 UTC, TorinAsakura commented on packages/payment-widget/src/interfaces/index.ts
> +export * from './theme.interfaces'
дубль?

2023-11-26 20:34 UTC, TorinAsakura commented on packages/payment-widget/src/ui/wrapper/button-wrapper.component.tsx
> +  return null
@Nelfimov FYI

2023-11-28 05:00 UTC, Nelfimov commented on packages/payment-widget/src/ui/wrapper/button-wrapper.component.tsx
> +  if (typeof children === 'function') {
Можешь воспользоваться нашим `@atls-ui-parts/condition`

2023-11-28 05:00 UTC, Nelfimov commented on packages/payment-widget/src/ui/wrapper/input-wrapper.component.tsx
> +  if (typeof children === 'function') {
То же замечание что по `ButtonWrapper`

2023-11-28 07:06 UTC, Nelfimov approved these changes

2023-11-28 15:55 UTC, Nelfimov requested changes

2023-11-28 15:55 UTC, Nelfimov commented on packages/payment-widget/README.md
> +# Применение
Давай красоты наведем:

1. Название пакета и краткое описание что делает.
2. Основной перечень пакетов/зависимостей и версий, которые использовали
3. Обязательно упомнять что написан с помощью `styled-components` и `@emotion`

В блоке "С темой виджета" прописать, что используется `styled-components` со стандартной темой. И лучше переименовать в, например, "Стоковая тема" или "Быстрый старт"

Блок "С темой проекта" лучше переименовать в "Кастомизация элементов виджета", где расписать общими словами, что для надобности кастомизировать инпуты и баттоны под веб-страницу/приложение мы предусмотрели и такое решение.

Так же распиши на всякий случай основные пропсы у виджета и что они значат.

2023-11-28 15:55 UTC, Nelfimov commented on packages/payment-widget/src/hooks/use-castom-button.hook.ts
> +import { ReactNode }            from 'react'
грамматика в названии файла

2023-11-28 21:56 UTC, TorinAsakura commented on packages/payment-widget/README.md
> +# Применение
стоковая - от слова stock, тут это не очень применимо, лучше "стандартная"

2023-11-29 08:26 UTC, Nelfimov approved these changes

2023-11-29 12:58 UTC, TorinAsakura requested changes

2023-11-29 12:58 UTC, TorinAsakura commented on packages/payment-widget/README.md
> +# @atls/react-payment-widget
сменить название пакета - tinkoff-payment-widget

2023-11-29 16:55 UTC, Nelfimov approved these changes

2023-11-29 21:39 UTC, TorinAsakura approved these changes

2023-11-29 21:39 UTC, merged