feat: react bump
atls/reactjs pull request #144
Opened 2024-09-16 09:09 UTC by effektivnayarabota1

closes https://github.com/atls/reactjs/issues/140

2024-09-16 09:10 UTC, effektivnayarabota1 commented
@Nelfimov 
в `npm` не нашел версию `18.2.2`, поставил `^18.2.0` - в `devDeps` & `peerDeps`

2024-09-16 09:11 UTC, Nelfimov requested changes
упали чеки

2024-09-16 09:11 UTC, Nelfimov commented on packages/upload/package.json
> +    "react": "^18.2.0"
дев зависимости должны быть фиксированными

2024-09-16 09:11 UTC, Nelfimov commented on packages/upload/package.json
>      "graphql": "^16.3.0",
почему это не трогал?

2024-09-16 09:27 UTC, effektivnayarabota1 commented
@Nelfimov 
тайпчек висит, на локалке тоже.
у нас же с `shdvor` была похожая ошибка?
![image](https://github.com/user-attachments/assets/748c7a4f-4738-47e3-90c0-fdbef9d9c8f2)

2024-09-16 09:30 UTC, Nelfimov commented
сноси yarn.lock, переустанавливай зависимости, убирай дубликаты зависимостей

2024-09-16 10:50 UTC, effektivnayarabota1 commented
@Nelfimov много ошибок линтера и тайпчека. поместить эту в другую задачу?

- была ошибка линтера - убрал `eslint` из корневого `package.json`
- ошибку `typecheck` - убрал, бампнув `@types/node` до 22й версии
- бампнул `@types/react` - до последней
- добавил `@types/tldjs` в `app-links` - потомучто была ошибка сборки пакета над которым работаю

---

- сейчас много `release`-ошибок - это я чтото наколдовал, или после твоих обновлений добавились проверки типов на релизе?

2024-09-16 10:52 UTC, Nelfimov commented
> @Nelfimov много ошибок линтера и тайпчека. поместить эту в другую задачу?

Линт - в другую отдельную. Не приоритет. 

Тайпчек - в рамках этой

> * сейчас много `release`-ошибок - это я чтото наколдовал, или после твоих обновлений добавились проверки типов на релизе?

Это новый бандл и окружение. Тайпчек и релизы надо фиксить.

2024-09-17 05:50 UTC, effektivnayarabota1 commented
@Nelfimov
работали над пакетом `@atls/react-upload`
- проверил тайпчки - у этого пакета нет ошибок
- проверил `prepack` - собирается без ошибок
- поднял минорную версию до `0.1.0`
- изменил тип пакета на `module`, пофиксил импорты
- ревью запросил

2024-09-17 07:06 UTC, merged